apiVersion: v1
kind: Pod
metadata:
    name: jenkins-pod
    labels:
        name: jenkins-pod
        app: jenkins-app
spec:
    containers:
    - name: jenkins-app
      image: jenkins
      ports:
          - containerPort: 80
