apiVersion: v1
kind: Service
metadata:
    name: myapp-service
    labels:
        name: myapp-service
        app: myfirstservice
spec:
    type: NodePort
    selector:
         app: myapp
         type: front-end
    ports:
      - targetPort: 80
        port: 80
