apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
spec:
    type: NodePort
    selector:
        name: jenkins-pod
        app: jenkins-app
    ports:
      - targetPort: 8080
        port: 80
        nodePort: 30080
