apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
    name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQW5YTWFsZjJvVmk3TEprU2RDT052RkQraUFWaDV2SEp4MVNRK2tUNjduYm0xCjlYZmhYMWZPWmtQQWxGYXRZQ1F5Nm5wTTI2NzFya1ZHd2xJZTZtWm1uTHQ4RVJnVGwxTFNRcHRzTC81Ym90YzcKenhrajBwT0MycVFSTEVYb3JHNHJkS2tuNTRWZ1JpUko3NzhmaFpBSCs2d244bm1aUkZKV1R6OUUyQ25VVitLVQorTmQ1WHk3OHJxQ0k4Uk5neGV0Tk1PQm14Zko0R3pLTHRqZUFtY1krblRCQisvTmRMUE9xNGVuUDliUmthQmwzCjlFSk4zcTk0Q0RadHlrMW1IWFNZTExwbjJnRkx1c0xNc1V5VVNMT3E1TWpHUFRpcktjdG82Y0VwVC81UlFHcDAKbmxpd1BpdFBuL3I4Qm5iZEg3SjNwMmU1cGtZdHMxeEJwUnlNaGRIcS93SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSkYwZmM0ZnE0TTdUd0wxS3diVWVPVy9MSFU4cUpZbVBJUnNYWkJtd25vMVB4a3JFbWk0CjZxT2ZiaHovVWZPRGorazVHaGd3b3VPMnVzRDArSFlEOTRKM2dzZ2FDUUVMY2hWREljQjNnNm1oR1RFWjFUTUMKSTFkUWt1YUM4OUd0Lzl6K29BTTY1SDNnQWw2QjhrQUpHMm1mZVFLdDRLVVRSenRQOGQ0T0FiaGRiZ1VDNE1xTgpIT0U3ZWtadVV1cklWazA5YjRyenlGVGR0ZDJvVmxGajB5TVhBZCt0UTlYVDRJSmltM3dCVWZ2NlQzN3diVGo5CkdKL0R1WWE3Y0NjWm5YeEZpanNVZW1uc3BmZlJsK0drS29QaEgrWjcyMXQrYkFTUGY2WEFOV0I1bTM4aWYzcEYKVUJtLzdFWGNvU1dwa0ptMmsxdGNlQStxcVNEdFkzdk1IRTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
