apiVersion: v1
kind: Secret
metadata:
  name: private-reg-cred
data:
    Name: cHJpdmF0ZS1yZWctY3JlZA==
    Username: ZG9ja191c2Vy
    Password: ZG9ja19wYXNzd29yZA==
    Server: bXlwcml2YXRlcmVnaXN0cnkuY29tOjUwMDA=
    Email: ZG9ja191c2VyQG15cHJpdmF0ZXJlZ2lzdHJ5LmNvbQ==
